spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시점에 테이블을 DROP 후 재생성
    properties:
      hibernate:
        format_sql: true
#        show_sql: true # System.out에 하이버네이트 실행 SQL문 출력

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  # 쿼리 파라미터 로그 남기기